# Generated by Django 2.0 on 2019-11-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=64, verbose_name='ID号')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('landtime', models.DateTimeField(auto_now=True, null=True, verbose_name='登录时间')),
                ('registertime', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('nickname', models.CharField(max_length=64, verbose_name='昵称')),
                ('sex', models.BooleanField(default=True, verbose_name='性别')),
                ('birthday', models.CharField(max_length=64, verbose_name='生日')),
                ('personalsign', models.CharField(max_length=128, verbose_name='个性签名')),
            ],
        ),
    ]
